window.practiceQuizPrompts = {
    en: {
        PRACTICE_QUIZ_PROMPT: PRACTICE_QUIZ_PROMPT_EN,
        PRACTICE_QUIZ_SCHEMA: PRACTICE_QUIZ_SCHEMA_EN
    },
    sr: {
        PRACTICE_QUIZ_PROMPT: PRACTICE_QUIZ_PROMPT_SR,
        PRACTICE_QUIZ_SCHEMA: PRACTICE_QUIZ_SCHEMA_SR
    },
    "sr-cyr": {
        PRACTICE_QUIZ_PROMPT: PRACTICE_QUIZ_PROMPT_SR_CYR,
        PRACTICE_QUIZ_SCHEMA: PRACTICE_QUIZ_SCHEMA_SR_CYR
    },
    id: {
        PRACTICE_QUIZ_PROMPT: PRACTICE_QUIZ_PROMPT_ID,
        PRACTICE_QUIZ_SCHEMA: PRACTICE_QUIZ_SCHEMA_ID
    },
    es: {
        PRACTICE_QUIZ_PROMPT: PRACTICE_QUIZ_PROMPT_ES,
        PRACTICE_QUIZ_SCHEMA: PRACTICE_QUIZ_SCHEMA_ES
    },
    ru: {
        PRACTICE_QUIZ_PROMPT: PRACTICE_QUIZ_PROMPT_RU,
        PRACTICE_QUIZ_SCHEMA: PRACTICE_QUIZ_SCHEMA_RU
    }
};
